name: 'Process Issues for Posting to Steem Action'
author: 'ETY001'
branding:
  # https://actions-cool.github.io/github-action-branding/
  icon: 'list'
  color: 'gray-dark'
description: 'Process issues for posting to Steem'
inputs:
  issue_number:
    description: 'If you give this number, this issue will set closed.'
    required: false
  repository:
    description: 'Your repository name, like username/repo'
    required: true
  token:
    description: 'The token of the repo'
    required: true
  tz:
    description: 'Timezone setting'
    required: false
    default: UTC
outputs:
  issue_number:
    description: 'The number of the issue that matches the filter'
  title:
    description: 'The title of the article that is found'
  content:
    description: 'The content of the article that is found'
  tags:
    description: 'The tags of the article that is found'
  reward:
    description: 'The reward setting of the article that is found'
runs:
  using: 'node16'
  main: 'dist/index.js'
